/* === BAHASA BARU - ENGINE MANDIRI === */
(function(){const NB={};let nbAktif=localStorage.getItem('newLanguage')||'';
function nbLoad(nama){return new Promise(resolve=>{if(!nama){resolve({});return}const r=nama.toLowerCase().trim();if(NB[r]){resolve(NB[r]);return}const s=sessionStorage.getItem('new_lang_'+r);if(s){try{NB[r]=JSON.parse(s);resolve(NB[r]);return}catch(e){}}const script=document.createElement('script');script.src=`bahasa_baru/bahasa_${r}.js`;script.onload=()=>{const data=window['new_'+r]||{};NB[r]=data;sessionStorage.setItem('new_lang_'+r,JSON.stringify(data));resolve(data)};script.onerror=()=>{console.error(`Gagal memuat bahasa_baru/bahasa_${r}.js`);resolve({})};document.head.appendChild(script)})}
function nbText(id,text){const el=document.getElementById(id);if(el&&text!=null)el.innerHTML=text}

function nbApply(data){if(!data||!Object.keys(data).length)return;if(data.title)document.title=data.title;const input=document.getElementById('urlInput');if(input&&data.placeholder)input.placeholder=data.placeholder;nbText('faqTitle',data.faqTitle);if(window.faqLoaded){nbText('faqQ1',data.faqQ1);nbText('faqA1',data.faqA1);nbText('faqQ2',data.faqQ2);nbText('faqA2',data.faqA2);nbText('faqQ3',data.faqQ3);nbText('faqA3',data.faqA3);nbText('faqQ4',data.faqQ4);nbText('faqA4',data.faqA4);nbText('faqQ5',data.faqQ5);nbText('faqA5',data.faqA5)}nbText('whyTitle',data.whyTitle);nbText('whyText',data.whyText);nbText('aboutTitle',data.aboutTitle);nbText('aboutText1',data.aboutText1);nbText('aboutText2',data.aboutText2);nbText('contactTitle',data.contactTitle);nbText('contactText1',data.contactText1);nbText('privacyTitle',data.privacyTitle);nbText('privacyText1',data.privacyText1);nbText('privacySub1',data.privacySub1);nbText('privacyText2',data.privacyText2);nbText('privacySub2',data.privacySub2);nbText('privacyText3',data.privacyText3);nbText('privacySub4',data.privacySub4);nbText('privacyText5',data.privacyText5);nbText('privacySub5',data.privacySub5);nbText('privacyText6',data.privacyText6);nbText('termsTitle',data.termsTitle);nbApplyGuide(data)}

function nbApplyGuide(data){const guide=document.getElementById('panduan'),box=document.getElementById('panduanBahasaBaru'),p=data&&data.panduan;if(!guide||!box||!p)return;guide.querySelectorAll('.lang-block').forEach(el=>el.style.display='none');box.style.display='block';box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:flex-start;position:relative;margin-bottom:12px;"><div><h2 style="font-size:40px;margin:0 0 4px 0;color:#000;font-weight:800;line-height:1.2;">${p.title}</h2><h3 style="font-size:18px;margin:0;color:#2c7a30;font-weight:700;font-style:italic;">${p.subtitle}</h3></div><div style="text-align:right;flex-shrink:0;margin-left:10px;margin-top:-5px;"><svg width="45" height="45" viewBox="0 0 100 100" fill="none" style="transform:rotate(15deg);"><path d="M20 10 C 70 10, 80 50, 75 80" stroke="#2c7a30" stroke-width="6" stroke-linecap="round" fill="none"/><path d="M60 68 L 75 82 L 85 68" stroke="#2c7a30" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg></div></div><h4 style="font-size:18px;margin:12px 0 10px;color:#1877f2;font-weight:700;">${p.heading}</h4><div style="font-size:18px;line-height:1.5;margin:22px 0 30px;color:#000;"><strong style="font-size:20px;color:#000;">${p.step1Title}</strong><br><img src="assets/panduan1.webp?v=1" alt="${p.alt1}" class="panduan-img" fetchpriority="high" decoding="async">${p.step1Text}</div><div style="font-size:18px;line-height:1.5;margin:22px 0 30px;color:#000;"><strong style="font-size:20px;color:#000;">${p.step2Title}</strong><br><img src="assets/panduan2.webp?v=1" alt="${p.alt2}" class="panduan-img langkah-2" decoding="async">${p.step2Text}</div><div style="font-size:18px;line-height:1.5;margin:22px 0 30px;color:#000;"><strong style="font-size:20px;color:#000;">${p.step3Title}</strong><br><img src="assets/panduan3.webp?v=1" alt="${p.alt3}" class="panduan-img" decoding="async">${p.step3Text}</div>`}

async function nbGanti(nama){if(!nama)return;const r=nama.toLowerCase().trim();nbAktif=r;localStorage.setItem('newLanguage',r);const data=await nbLoad(r);nbApply(data);const btn=document.getElementById('bahasaBaruBtn');if(btn&&data.bendera)btn.innerHTML='<span class="ikon-globe"></span>'}
async function nbPulihkan(){if(!nbAktif)return;const data=await nbLoad(nbAktif);if(!data||!Object.keys(data).length)return;nbApply(data);const btn=document.getElementById('bahasaBaruBtn');if(btn)btn.innerHTML='<span class="ikon-globe"></span>'}

window.nbPulihkan=nbPulihkan;
document.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('bahasaBaruBtn'),d=document.getElementById('bahasaBaruDropdown');if(!b||!d)return;b.addEventListener('click',e=>{e.stopPropagation();d.style.display=d.style.display==='block'?'none':'block'});d.addEventListener('click',e=>{const item=e.target.closest('[data-new-lang]');if(!item)return;e.stopPropagation();const lang=item.getAttribute('data-new-lang');d.style.display='none';nbGanti(lang)});document.addEventListener('click',e=>{if(!b.contains(e.target)&&!d.contains(e.target))d.style.display='none';const original=e.target.closest('.lang-btn');if(original){localStorage.removeItem('newLanguage');nbAktif='';const box=document.getElementById('panduanBahasaBaru');if(box)box.style.display='none'}})})})();